/*
 * Module 4.x — UART communication ESP32 ↔ STM32
 * STM32 side — Black Pill F411CEU6, STM32CubeIDE / HAL
 *
 * Wiring:
 *   STM32 USART1 TX (PA9)   →  ESP32 RX2 (GPIO16)
 *   STM32 USART1 RX (PA10)  ←  ESP32 TX2 (GPIO17)
 *   GND                      —  GND
 *
 *   Button  : PC13 (onboard USER button, active LOW)
 *   LED     : PC13… no — use PB12 (external) or the onboard LED on PC13 is
 *             tied to the button on Black Pill, so:
 *   LED out : PB2  (external, active HIGH via 330Ω)
 *
 * Protocol: same as ESP32 side
 *   0xA1 — toggle LED
 *   0xB1 — ACK
 *
 * CubeMX settings used to generate the project skeleton:
 *   USART1: Async, 115200 8N1, TX=PA9 RX=PA10, global IRQ enabled
 *   GPIO PC13: Input, Pull-Up (USER button)
 *   GPIO PB2:  Output Push-Pull (LED)
 *   SYS: SysTick timebase
 */

#include "main.h"      // generated by CubeMX
#include <string.h>
#include <stdio.h>

// ─── Config ─────────────────────────────────────────────────
#define CMD_TOGGLE      0xA1
#define CMD_ACK         0xB1

#define BTN_PORT        GPIOC
#define BTN_PIN         GPIO_PIN_13   // active LOW

#define LED_PORT        GPIOB
#define LED_PIN         GPIO_PIN_2

#define DEBOUNCE_MS     50
#define LOG_PERIOD_MS   2000

// ─── Handles (declared extern, defined in CubeMX-generated main.c) ──
extern UART_HandleTypeDef huart1;

// ─── State ──────────────────────────────────────────────────
static uint8_t  rx_byte        = 0;
static volatile uint8_t rx_flag = 0;   // set by UART RX ISR callback

static uint8_t  led_state      = 0;
static uint32_t tx_count       = 0;
static uint32_t rx_count       = 0;

// ─── Helpers ────────────────────────────────────────────────
static void led_set(uint8_t on) {
    led_state = on;
    HAL_GPIO_WritePin(LED_PORT, LED_PIN, on ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

static void led_toggle(void) {
    led_set(!led_state);
}

static void uart_send_byte(uint8_t b) {
    HAL_UART_Transmit(&huart1, &b, 1, 100);
}

// Re-arm single-byte RX interrupt after each reception
static void uart_rx_arm(void) {
    HAL_UART_Receive_IT(&huart1, &rx_byte, 1);
}

// ─── HAL UART RX callback (called from IRQ) ─────────────────
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart) {
    if (huart->Instance == USART1) {
        rx_flag = 1;
        uart_rx_arm(); // re-arm immediately
    }
}

// ─── Debounced button ────────────────────────────────────────
static uint8_t btn_pressed(void) {
    static uint8_t  last_raw    = 1;
    static uint8_t  stable      = 1;
    static uint32_t last_ms     = 0;

    uint8_t raw = (HAL_GPIO_ReadPin(BTN_PORT, BTN_PIN) == GPIO_PIN_RESET) ? 0 : 1;
    if (raw != last_raw) { last_raw = raw; last_ms = HAL_GetTick(); }
    if ((HAL_GetTick() - last_ms) >= DEBOUNCE_MS && raw != stable) {
        stable = raw;
        if (stable == 0) return 1; // falling edge = press
    }
    return 0;
}

// ─── Log via USART2 (debug, goes to ST-Link VCP) ────────────
// USART2 TX = PA2, configured in CubeMX as debug console
extern UART_HandleTypeDef huart2;

static void log_str(const char *s) {
    HAL_UART_Transmit(&huart2, (uint8_t *)s, strlen(s), 100);
}

static char log_buf[96];
#define LOG(...) do { snprintf(log_buf, sizeof(log_buf), __VA_ARGS__); log_str(log_buf); } while(0)

// ─── app entry (called from CubeMX-generated main after HAL_Init) ──
void app_run(void) {
    LOG("\r\n[BOOT] UART bridge — STM32 side (F411 Black Pill)\r\n");
    LOG("[INFO] USART1 TX=PA9 -> ESP32 GPIO16  RX=PA10 <- ESP32 GPIO17\r\n");
    LOG("[INFO] USART2 TX=PA2 -> ST-Link VCP (debug)\r\n");
    LOG("[INFO] Button PC13  LED PB2\r\n");
    LOG("[INFO] Baud: 115200  Protocol: 0xA1=toggle 0xB1=ACK\r\n");
    LOG("--- Ready ---\r\n\r\n");

    led_set(0);
    uart_rx_arm();  // arm first RX

    uint32_t last_hb = 0;

    while (1) {
        // ── Our button → send toggle to ESP32 ───────────────
        if (btn_pressed()) {
            uart_send_byte(CMD_TOGGLE);
            tx_count++;
            LOG("[UART TX] 0xA1 -> ESP32 toggle LED\r\n");
        }

        // ── Received byte from ESP32 ─────────────────────────
        if (rx_flag) {
            uint8_t cmd = rx_byte;
            rx_flag = 0;

            if (cmd == CMD_TOGGLE) {
                led_toggle();
                rx_count++;
                LOG("[UART RX] 0xA1 <- ESP32 button -> LED %s\r\n",
                    led_state ? "ON" : "OFF");

                // ACK
                uart_send_byte(CMD_ACK);
                LOG("[UART TX] 0xB1 -> ESP32 ACK\r\n");

            } else if (cmd == CMD_ACK) {
                LOG("[UART RX] 0xB1 <- ESP32 ACK\r\n");
            } else {
                LOG("[UART RX] unknown: 0x%02X\r\n", cmd);
            }
        }

        // ── Heartbeat ────────────────────────────────────────
        uint32_t now = HAL_GetTick();
        if (now - last_hb >= LOG_PERIOD_MS) {
            last_hb = now;
            LOG("[HB] uptime=%lus  tx=%lu  rx=%lu  led=%s\r\n",
                now / 1000, tx_count, rx_count,
                led_state ? "ON" : "OFF");
        }
    }
}
